### ISSUE TITLE
Convert library from CommonJS to ES Module

### ISSUE THREAD

**Issue by eliot-akira** [TangibleInc/tangible-roller#5]
Eventually the library should be transitioned from CommonJS style `require` statements like:

```js
const path = require('path')
```

..into ES Module style using `import`, which is the new standard.

```js
import path from 'path'
```

Luckily, since the Roller library is used only as a command-line tool and not meant to be imported as a module, this change shouldn't affect users of the library with projects that are still on CommonJS.

The change also involves replacing `module.exports` with `export` statements.

---

@nicolas-jaussaud I wanted to let you know about this change in advance, just in case it might have unintended effects. In the JS ecosystem the transition has been a bit rough, as some popular libraries converted too early and broke compatibility. It should be fine in our case though.

I was reminded of this when you mentioned `tangible.config.js` starting with:

```js
module.exports = { ... }
```

Gradually, I'd like to convert projects (plugins, etc.) to use ES Module style imports. This can be enabled in `package.json` with a single line: 

```js
  "type": "module",
```

And changing the config file to export like this:

```js
export default { ... }
```

This is already supported in the current version of Roller, as it uses `await import()` to load the config file instead of `require()`.

**Comment by nicolas-jaussaud** [comment]
Oh I see, I will try to test and make the change each time I encounter a project that uses the old syntax

Thank you for the explanation!

**Comment by eliot-akira** [comment]
Resolved:
- #8
